### ISSUE TITLE
add option for using server-side env variables

### ISSUE THREAD

**Issue by paulrudy** [Cyber-Logical-Development/astro-turnstile#102]
Thanks for this integration!

I'd like to suggest an option to declare the cloudflare keys as server-side env variables (`process.env.TURNSTILE_SITE_KEY` and `process.env.TURNSTILE_SECRET_KEY`) instead of declaring them in the `.env` file. That way, for codebases that may be deployed to github, for example, don't need to include secret keys that would be viewable in the repo.

**Comment by hkbertoson** [comment]
The .env file is only server side. It shouldn't be committed to your project. Not quite sure what you are looking for? Could you elaborate?

**Comment by paulrudy** [comment]
I'm sorry, you're right. For some reason, I had `.env` commented out in my `.gitignore`. Fortunately, I wasn't using it for anything and was relying only on server env variables in Vercel.
