### ISSUE TITLE
Make it possible to change the label of the submit button

### ISSUE THREAD

**Issue by tobyhage** [Cyber-Logical-Development/astro-turnstile#117]
Hello,

Thank you for this package. On this moment it is not possible to change the label of the submit button.
It would be a nice feature and i think no very difficult to implement to make this string customizable.

`<slot name="buttons">
     <button type="submit" class="at-turnstile-submit-button">Submit</button>
</slot>`

**Comment by hkbertoson** [comment]
Just published 2.0.1 which has this change.
