### ISSUE TITLE
Make it possible to make widget with height: 0px; 

### ISSUE THREAD

**Issue by tobyhage** [Cyber-Logical-Development/astro-turnstile#118]
On this moment it is not possible to make the width a zero height.
i use the invisible turnstile widget and then i lost 65px of margin in my form.

So it would be nice to add a zero height option.

Thank you!

`const sizes: Sizes = {
	normal: { height: "65px", width: "300px", minWidth: "300px" },
	flexible: { height: "65px", width: "100%", minWidth: "300px" },
	compact: { height: "140px", width: "150px", minWidth: "150px" },
};`

**Comment by hkbertoson** [comment]
I can do this. But the reason it's hardcoded is because Cloudflare says to keep the spacing for placeholder purposes in case their API demands it to be visible.

So it would be a use at your own risk kinda thing.

**Comment by tobyhage** [comment]
In the meantime i have made a custom solution, because i had another issue with this plugin.
I don't know which problem, so i can't tell you anymore, sorry.

Maybe this request is also not so important. I think a user can solve the margin with a negative margin with css.
I will close this ticket.
